### PR TITLE
Travis to github

### LINKED ISSUE #82: Migrate Travis -> Github Actions
Travis will be limited open source projects build time soon, so we need to transition to github actions. 

Take a look at how we did it [open discussions](https://github.com/mitodl/open-discussions/pull/3204) or [bootcamps](https://github.com/mitodl/bootcamp-ecommerce/pull/1086) or [micromasters](https://github.com/mitodl/micromasters/pull/4682)

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### What are the relevant tickets?
Fixes #82 

#### What's this PR do?
Switches from Travis to Github actions.

#### How should this be manually tested?
Checking that all required parts are integrated & Github Actions pass successfully.

#### Where should the reviewer start?
Looking at the details of GitHub actions result page.

### CODE REVIEW

**Comment by noisecapella** [comment]
I think the test is failing because the docker mount point is incorrect. You just need to adjust your last line. Can you try changing `$PWD/..` to `$PWD/..:/rapid-response-xblock`?

**Comment by arslanashraf7** [comment]
> I think the test is failing because the docker mount point is incorrect. You just need to adjust your last line. Can you try changing `$PWD/..` to `$PWD/..:/rapid-response-xblock`?

@noisecapella Yes that makes sense, Let me give it a try.

**Comment by noisecapella** [comment]
In addition to the `CapaDescriptor` problem @gsidebo mentioned in a different PR it looks like pylint is erroring. That's coming from devstack so I'm not sure if master is just broken or if there's a dependency problem, if the problem is with Python 3.8 being used there, etc. One thing we could try is checking out a branch corresponding to a stable release branch rather than master

**Comment by pdpinch** [comment]
For our use, I think the most relevant branch for testing would be mitodl/mitx/koa 

> One thing we could try is checking out a branch corresponding to a stable release branch rather than master

**Comment by arslanashraf7** [comment]
@pdpinch @noisecapella You are right. 

Checking out the `mitodl/mitx/koa` on CI for tests fixed the `pylint` error that we were facing.
There were many other issues other than `CapaDescriptor` as well that are fixed in a separate PR https://github.com/mitodl/rapid-response-xblock/pull/87 to keep the things tidy. (That separate PR does refactoring, and the build is passing there as well - After Koa branch checkout)

So, Once we go ahead & merge https://github.com/mitodl/rapid-response-xblock/pull/87. We can simply rebase this PR and this should be working as well.

**Comment by pdpinch** [comment]
#87 is merged now. Is this unblocked?

**Comment by arslanashraf7** [comment]
@pdpinch Yes, I have removed `Blocked` label from this.

**Pull request merged**
