### PR TITLE
Fixed missing events for Koa

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### What are the relevant tickets?
It looked associated with https://github.com/mitodl/rapid-response-xblock/issues/85 but this fix is out of scope for the aforementioned issue now since that issue is more related to fixing the broken tests and this PR resolves another one where our events were broken, Though some initial details can be seen on this ticket.

#### What's this PR do?
Changes event backends configurations, With Koa we were not receiving the events for rapid response e.g. our send method for events wasn't getting called https://github.com/mitodl/rapid-response-xblock/blob/dbc6bfbaab0f583680816ba86f0d43c84c931d58/rapid_response_xblock/logger.py#L76. Thus there were no entries getting created in for `RapidResponseSubmission` model. The live bar chart was not getting the update as well & submitted responses by a user would always be 0.

**Note:** 
- In order to get the events I had to change the tracking backend key from `TRACKING_BACKENDS` to `EVENT_TRACKING_BACKENDS` in the settings, inspired by https://event-routing-backends.readthedocs.io/en/latest/getting_started.html. 
- Now the new events that I started getting had a slight change in their JSON structure so I made some tweaks there to support this new JSON.

#### How should this be manually tested?
- Setup Koa release of OpenEdx
- Use `mitx/koa` branch of `edx-platform` from `mitodl`.
- Install this branch of rapid response block & make all the configurations mentioned in the `README`, except for setting `ALLOW_ALL_ADVANCED_COMPONENTS` since the README isn't quite updated and this setting doesn't work.
- I know it might take more effort, but it would be more in our interest if we could do A/B testing on this one.

#### Where should the reviewer start?
Setup a rapid response choice question - I think!

#### Any background context you want to provide?
This repo hasn't been updated within recent times while edX made some changes in the platform which somehow started to affect this xBlock and yet there are some tests failing for a long time, But that is of less priority for this issue I think! One small change to reflect edx updates is optimization in import in our logger.

#### Screenshots (if appropriate)
Screenshot 2020-12-16 at 9 10 20 PM

Screenshot 2020-12-16 at 9 09 59 PM

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@pdpinch This is the PR I hope, that will supposedly fix the issue of the live response. I have also attached the screenshots in the description -  I'm not sure if we should create a `koa` branch here as well. I've also not associated this PR with https://github.com/mitodl/rapid-response-xblock/issues/85, since that issue has a different context. Maybe, If you could create a new issue and we associate it with this PR.

@noisecapella I tried to add all the possible details in the description and I apologize if something isn't clear. Please let me know if you feel something is irrelevant or maybe if this PR is our step in the right direction.

**Comment by noisecapella** [comment]
Testing this out now. Do you know where I can find the event change in the edX docs?

**Comment by arslanashraf7** [comment]
@noisecapella I wasn't able to find the exact document for that change but one thing was sure that we weren't receiving the events until I changed `TRACKING_BACKENDS ` to `EVENT_TRACKING_BACKENDS` looking at https://event-routing-backends.readthedocs.io/en/latest/getting_started.html. After the new backend setting the structure of event JSON was changed so I had to change how we were manipulating the event. I have the new JSON, I'm posting it below for reference:

```
{
	'name': 'problem_check',
	'timestamp': datetime.datetime(2020, 12, 17, 15, 4, 55, 453466, tzinfo = < UTC > ),
	'data': {
		'state': {
			'seed': 1,
			'student_answers': {
				'05b17318347a445db0bfb0f84b87b29d_2_1': 'choice_1'
			},
			'has_saved_answers': False,
			'correct_map': {
				'05b17318347a445db0bfb0f84b87b29d_2_1': {
					'correctness': 'correct',
					'npoints': None,
					'msg': '',
					'hint': '',
					'hintmode': None,
					'queuestate': None,
					'answervariable': None
				}
			},
			'input_state': {
				'05b17318347a445db0bfb0f84b87b29d_2_1': {}
			},
			'done': True
		},
		'problem_id': 'block-v1:Edx+CS00001+2020_Q4+type@problem+block@05b17318347a445db0bfb0f84b87b29d',
		'answers': {
			'05b17318347a445db0bfb0f84b87b29d_2_1': 'choice_2'
		},
		'grade': 0,
		'max_grade': 1,
		'correct_map': {
			'05b17318347a445db0bfb0f84b87b29d_2_1': {
				'correctness': 'incorrect',
				'npoints': None,
				'msg': '',
				'hint': '',
				'hintmode': None,
				'queuestate': None,
				'answervariable': None
			}
		},
		'success': 'incorrect',
		'attempts': 48,
		'submission': {
			'05b17318347a445db0bfb0f84b87b29d_2_1': {
				'question': Markup('Add the question text, or prompt, here. This text is required.'),
				'answer': 'an incorrect answer',
				'response_type': 'multiplechoiceresponse',
				'input_type': 'choicegroup',
				'correct': False,
				'variant': '',
				'group_label': ''
			}
		}
	},
	'context': {
		'course_id': 'course-v1:Edx+CS00001+2020_Q4',
		'course_user_tags': {},
		'session': '013560dc72d67a18e4da65f69a5261da',
		'user_id': 8,
		'username': 'staff',
		'ip': '172.18.0.1',
		'host': 'edx.odl.local:18000',
		'agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36',
		'path': '/courses/course-v1:Edx+CS00001+2020_Q4/xblock/block-v1:Edx+CS00001+2020_Q4+type@problem+block@05b17318347a445db0bfb0f84b87b29d/handler/xmodule_handler/problem_check',
		'referer': 'http://edx.odl.local:18000/courses/course-v1:Edx+CS00001+2020_Q4/courseware/1923b034a414407f851c863039c22572/32dbfefa9fab48debaab4c9dccdd58ea/?activate_block_id=block-v1%3AEdx%2BCS00001%2B2020_Q4%2Btype%40sequential%2Bblock%4032dbfefa9fab48debaab4c9dccdd58ea',
		'accept_language': 'en-US,en;q=0.9',
		'client_id': None,
		'org_id': 'Edx',
		'module': {
			'display_name': 'Multiple Choice',
			'usage_key': 'block-v1:Edx+CS00001+2020_Q4+type@problem+block@05b17318347a445db0bfb0f84b87b29d'
		},
		'asides': {},
		'event_source': 'server',
		'page': 'x_module'
	}
}
```

**Comment by pdpinch** [comment]
Doing a little git-blame digging, it looks like the change to the SETTINGS name was done about 6 months ago, probably in version 1.0.0

https://github.com/edx/event-tracking/releases/tag/1.0.0

https://github.com/edx/event-tracking/blame/6b2bbfe72d082b27f44a1b03f65c586f87931ed0/eventtracking/django/django_tracker.py#L13

**Comment by gsidebo** [comment]
I finally have devstack running with the Koa release, but I am unable to get rapid response working end-to-end with this branch. When I try to open a problem for responses in LMS, I get this exception (important lines included):

```
  File "/edx/app/edxapp/venvs/edxapp/src/rapid-response-xblock/rapid_response_xblock/block.py", line 137, in toggle_block_open_status
    run = RapidResponseRun.objects.create(
...
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1364, "Field 'name' doesn't have a default value")
```
Basically the `RapidResponseRun.objects.create()` line is failing in `rapid_response_xblock.block.RapidResponseAside.toggle_block_open_status`. That model doesn't have a `name` field, so presumably this has something to do with the `problem_usage_key` or `course_key` objects. In my case, the `wrapped_block_usage_key` does have a `name` value. I'll keep hacking away at this but thought I should let you know in case you ran into this

**Comment by gsidebo** [comment]
@arslanashraf7 I figured out what was happening. There were some changes to the model that for some reason have never been reflected in a migration. I'm not sure how this could have ever worked without that migration. I created a migration locally and pushed it to this branch (and the other PR) and now rapid response seems to work again. Can you also try it out and make sure it works?

**Comment by arslanashraf7** [comment]
@gsidebo I checked and I saw that this migration was already applied to my database which possibly happened when I applied the migrations in the LMS itself with rapid response mounted in when I was figuring out the issues when the tests were failing, That's why it worked for me and I didn't see the issue you mentioned above since the migration was already applied on my database.

You are right to push the new migration, I unapplied my old migration (issue occurs) and reapplied with the new one and it continues to works fine 👍

**Comment by gsidebo** [comment]
Closing in favor of #87

**Pull request closed without merging**
