### PR TITLE
Fixes: Page scrolls when closing rapid response problem

### PR DESCRIPTION
**Pull request by asadiqbal08**
#### What are the relevant tickets?
fixes: #122 

#### What's this PR do?
Fix the page scroll issue as mentioned in the ticket.

#### How should this be manually tested?
Follow the [Readme Steps](https://github.com/mitodl/rapid-response-xblock) to install the Rapid Response block in Studio and CMS. 
Verify that the page should not be scroll on either opening or closing the problem in LMS.

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@asadiqbal08 Can you look at the failing tests?

**Comment by asadiqbal08** [comment]
@arslanashraf7 I am not sure why integration tests are failing over here. I looked around but the reasons of failing does not seem to related to my changes. 

As a TestCase, I reverted my changes in [2nd commit](https://github.com/mitodl/rapid-response-xblock/pull/123/commits/c9fb21f07db1a7ea3e1a26e3498e7125db776640) but the build is failing again. 

@pdpinch do u have some thoughts about the pipeline flow here ?

**Comment by asadiqbal08** [comment]
The `ci` actions are pointing to `master` of [mitodl for edx-platform](https://github.com/mitodl/rapid-response-xblock/blob/master/.github/workflows/ci.yml#L25)

**Comment by arslanashraf7** [comment]
> @arslanashraf7 I am not sure why integration tests are failing over here. I looked around but the reasons of failing does not seem related to my changes.
> 
> As a TestCase, I reverted my changes in [2nd commit](https://github.com/mitodl/rapid-response-xblock/pull/123/commits/c9fb21f07db1a7ea3e1a26e3498e7125db776640) but the build is failing again.


The initial look at the failing logs gives me an impression that something in the course structure has been changed. The tests are mostly failing in the setup part of our test suit and complaining about the index/course lookup being unavailable. I think we might have to look back a little to see the changes recently done in the courseware lookup in the edX.

Since the tests are failing and it's possible that our functionality might also be broken. So, while making this change did you test it and see that the xBlock is working fine?

>The ci actions are pointing to master of [mitodl for edx-platform](https://github.com/mitodl/rapid-response-xblock/blob/master/.github/workflows/ci.yml#L25)

In our django upgrade PR I mentioned the reason for that [here](https://github.com/mitodl/rapid-response-xblock/pull/111/files#r728890729) because our tests were failing unnecessarily. And I think it's time to take it back to `mitx/maple`. Can you try running the tests on https://github.com/mitodl/edx-platform/tree/mitx/maple and see if we get different results in the CI?

**Comment by asadiqbal08** [comment]
@arslanashraf7 can you test the scroll fix here ?

**Review by arslanashraf7 — APPROVED** [review]
Looks good & works well 👍 We can merge this.

As per the discussion regarding CI above, I've created a separate ticket https://github.com/mitodl/rapid-response-xblock/issues/124 so that we can take a look at that in a separate PR.

**Pull request merged**
